"""XRay (VLESS+XHTTP) inbound — public-facing proxy that re-egresses
client traffic through the AmneziaWG tunnel.

This is the cloud-VM-only counterpart to the home gateway's split-tunnel
LAN proxy: clients on the public internet (Android / Win / Mac apps that
speak VLESS) dial the XHTTP path on vpn.example.com:443, get
unwrapped by xray running on the gateway, and then their traffic is
re-egressed through amn0 (AmneziaWG) — same exit IPs as everyone on
the LAN sees.

Architecture:
  client app  ──TLS──>  nginx :443/<XHTTP_PATH>  ──plain HTTP/1.1──>
    xray :8443 (VLESS-in)  ──SO_MARK=1──>
      ip rule fwmark 0x1 -> table 100 -> amn0 (AmneziaWG)  ──>  internet

`server.json` is generated by vpngw-xray-render-config.py from
server-params.json + clients.json. The API never touches server.json
directly; it manipulates clients.json via the helper scripts.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path

from fastapi import APIRouter, Body

from config import (
    SCRIPTS_DIR,
    XRAY_CLIENTS_FILE,
    XRAY_DIR,
)
from models.common import error, ok
from services import system_commands as sys_cmd
from services.script_runner import run_command

router = APIRouter(prefix="/xray", tags=["xray"])

XRAY_SERVICE = "vpngw-xray"
# Same constraint as scripts/vpngw-xray-add-client.py — short, safe.
_NAME_RE = re.compile(r"^[A-Za-z0-9_-]{1,32}$")
_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)

PARAMS_FILE = XRAY_DIR / "server-params.json"
ADD_CLIENT = SCRIPTS_DIR / "vpngw-xray-add-client.py"
REMOVE_CLIENT = SCRIPTS_DIR / "vpngw-xray-remove-client.py"
STATS_SCRIPT = SCRIPTS_DIR / "vpngw-xray-stats.py"


def _read_params() -> dict:
    """Read server-params.json (XHTTP path + public host)."""
    try:
        return json.loads(PARAMS_FILE.read_text())
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def _read_clients() -> list[dict]:
    try:
        data = json.loads(XRAY_CLIENTS_FILE.read_text())
        return data if isinstance(data, list) else []
    except (FileNotFoundError, json.JSONDecodeError):
        return []


@router.get("/status")
async def status():
    """Aggregated xray state for the dashboard widget.

    Shape:
      {
        "service":  {name, active, state, enabled},
        "configured": bool,         // server-params.json + clients.json present?
        "public_host": "vpn.example.com",
        "client_count": N,
        "stats": {
          "inbound_uplink":   <bytes>,
          "inbound_downlink": <bytes>,
          "outbound_uplink":  <bytes>,
          "outbound_downlink": <bytes>,
        }
      }

    `stats` is omitted if xray isn't running or the stats API can't be
    reached — UI must handle missing keys.
    """
    svc = await sys_cmd.get_service_status(XRAY_SERVICE)
    params = _read_params()
    clients = _read_clients()
    configured = bool(params.get("xhttp_path") and params.get("public_host"))

    body: dict = {
        "service":      svc.model_dump(),
        "configured":   configured,
        "public_host":  params.get("public_host", ""),
        "client_count": len(clients),
    }

    # Stats only make sense while the service is running. Calling the
    # stats script when xray is down would just hang on the gRPC dial.
    if svc.active and STATS_SCRIPT.exists():
        result = await run_command(str(STATS_SCRIPT), timeout=6)
        if result.success:
            try:
                body["stats"] = json.loads(result.output)
            except json.JSONDecodeError:
                body["stats"] = {"error": "stats parse failed"}
        else:
            body["stats"] = {"error": result.output.strip()[:200]}

    return ok(body)


@router.get("/clients")
async def list_clients():
    """List registered VLESS clients (excluding share URLs, which the
    UI fetches on demand via /clients/{uuid}/share-url to avoid leaking
    every UUID into the status poll payload)."""
    clients = _read_clients()
    return ok({"clients": clients, "count": len(clients)})


@router.post("/clients")
async def add_client(payload: dict = Body(...)):
    """Generate a new client UUID and append it to clients.json.

    Body: {"name": "<label>"}  — label must match [A-Za-z0-9_-]{1,32}
    Returns the new client record + a copy-pasteable vless:// share URL.
    """
    name = (payload or {}).get("name", "").strip()
    if not _NAME_RE.match(name):
        return error(
            f"invalid name {name!r} — must match {_NAME_RE.pattern}"
        )
    if not ADD_CLIENT.exists():
        return error(f"helper script missing: {ADD_CLIENT}")

    # `--json` makes the helper print a single JSON line we can parse.
    result = await run_command(str(ADD_CLIENT), "--name", name, "--json")
    if not result.success:
        return error(f"add-client failed: {result.output.strip()[:500]}")

    # The helper prints other diagnostics + the JSON line. Grab the
    # last non-empty line and parse it.
    last_line = ""
    for line in result.output.splitlines():
        s = line.strip()
        if s:
            last_line = s
    try:
        client = json.loads(last_line)
    except json.JSONDecodeError:
        return error(
            f"add-client produced non-JSON output: {result.output.strip()[:500]}"
        )

    svc = await sys_cmd.get_service_status(XRAY_SERVICE)
    return ok({"client": client, "service": svc.model_dump()},
              log=f"added xray client {name} ({client.get('uuid')})")


@router.delete("/clients/{client_uuid}")
async def remove_client(client_uuid: str):
    """Revoke a client by UUID and restart xray so the live connection
    (if any) drops immediately."""
    if not _UUID_RE.match(client_uuid):
        return error(f"not a valid UUID: {client_uuid!r}")
    if not REMOVE_CLIENT.exists():
        return error(f"helper script missing: {REMOVE_CLIENT}")

    result = await run_command(
        str(REMOVE_CLIENT), "--uuid", client_uuid, "--json"
    )
    if not result.success:
        return error(f"remove-client failed: {result.output.strip()[:500]}")

    svc = await sys_cmd.get_service_status(XRAY_SERVICE)
    return ok({"service": svc.model_dump()},
              log=f"revoked xray client {client_uuid}")


@router.get("/clients/{client_uuid}/share-url")
async def get_share_url(client_uuid: str):
    """Build the vless:// share URL for an existing client.

    We don't store URLs (they're a pure function of UUID + params), so
    this just looks the client up by UUID, then reconstructs the same
    string vpngw-xray-add-client.py would print.
    """
    if not _UUID_RE.match(client_uuid):
        return error(f"not a valid UUID: {client_uuid!r}")
    clients = _read_clients()
    found = next((c for c in clients
                  if c.get("uuid", "").lower() == client_uuid.lower()),
                 None)
    if not found:
        return error(f"no such client: {client_uuid}")
    params = _read_params()
    if not params.get("public_host") or not params.get("xhttp_path"):
        return error("xray is not initialised — server-params.json missing")

    # Import here to keep the script's URL-builder as the canonical
    # implementation. (Local import avoids polluting module scope and
    # only fires when this endpoint is hit.)
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "xray_add_client", str(ADD_CLIENT)
    )
    if spec and spec.loader:
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        url = mod.share_url(found["uuid"], found.get("name", "client"), params)
    else:
        url = ""

    return ok({"client": found, "share_url": url})


@router.get("/clients/{client_uuid}/qr")
async def get_qr_svg(client_uuid: str):
    """Return an SVG QR-code for the client's share URL.

    Shells out to `qrencode -t SVG` — the dashboard inlines the resulting
    SVG into the DOM so it scales cleanly and stays crisp on hi-DPI.
    Wrapped in our usual {status, data:{svg}} envelope so the existing
    API.get() pipeline picks it up; the frontend just drops `data.svg`
    into innerHTML.

    Same UUID lookup as /share-url — reconstructed via the helper script's
    share_url() so QR and copy-to-clipboard never go out of sync.
    """
    if not _UUID_RE.match(client_uuid):
        return error(f"not a valid UUID: {client_uuid!r}")

    qrencode_bin = shutil.which("qrencode")
    if not qrencode_bin:
        return error("qrencode binary not found — install package qrencode")

    clients = _read_clients()
    found = next((c for c in clients
                  if c.get("uuid", "").lower() == client_uuid.lower()),
                 None)
    if not found:
        return error(f"no such client: {client_uuid}")
    params = _read_params()
    if not params.get("public_host") or not params.get("xhttp_path"):
        return error("xray is not initialised — server-params.json missing")

    # Reconstruct share URL via the same helper as /share-url.
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "xray_add_client", str(ADD_CLIENT)
    )
    url = ""
    if spec and spec.loader:
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        url = mod.share_url(found["uuid"], found.get("name", "client"), params)
    if not url:
        return error("failed to build share URL")

    # `-l M` = medium error-correction; the URL is too long for `H` to
    # fit comfortably without a huge code, and `M` is the QR-spec default.
    # `-m 1` keeps the white border tiny so the QR fills the SVG box.
    proc = subprocess.run(
        [qrencode_bin, "-t", "SVG", "-l", "M", "-m", "1", "-o", "-", url],
        capture_output=True,
        text=True,
        timeout=5,
    )
    if proc.returncode != 0 or not proc.stdout:
        return error(
            f"qrencode failed: {proc.stderr.strip()[:200] or 'no output'}"
        )

    return ok({"svg": proc.stdout, "url": url})


@router.post("/enable")
async def enable():
    """Start vpngw-xray + enable on boot. Refuses if no clients are
    configured — xray would come up but reject every connection, which
    is rarely what the operator wanted."""
    if not _read_clients():
        return error("no clients configured — add at least one first")
    enable_log = await sys_cmd.run_systemctl("enable", XRAY_SERVICE)
    start_log = await sys_cmd.service_action(XRAY_SERVICE, "start")
    svc = await sys_cmd.get_service_status(XRAY_SERVICE)
    return ok({"service": svc.model_dump()},
              log=(enable_log + "\n" + start_log).strip())


@router.post("/disable")
async def disable():
    """Stop and disable vpngw-xray."""
    stop_log = await sys_cmd.service_action(XRAY_SERVICE, "stop")
    disable_log = await sys_cmd.run_systemctl("disable", XRAY_SERVICE)
    svc = await sys_cmd.get_service_status(XRAY_SERVICE)
    return ok({"service": svc.model_dump()},
              log=(stop_log + "\n" + disable_log).strip())


@router.post("/restart")
async def restart():
    """Restart vpngw-xray (e.g. after editing server-params manually)."""
    log = await sys_cmd.service_action(XRAY_SERVICE, "restart")
    svc = await sys_cmd.get_service_status(XRAY_SERVICE)
    return ok({"service": svc.model_dump()}, log=log)
