#!/bin/bash
# Generate dnsmasq ipset configs from /opt/vpngateway/config/domains/*.lst.
#
# Each .lst file becomes its own dnsmasq drop-in, all populating the same
# vpn_domains ipset. Splitting by file is purely organisational — it lets
# operators add/remove a category (e.g. AWS, Cloudflare, banking) atomically.
#
#   config/domains/main.lst        -> /etc/dnsmasq.d/vpn-domains-main.conf
#   config/domains/aws.lst         -> /etc/dnsmasq.d/vpn-domains-aws.conf
#   config/domains/cloudflare.lst  -> /etc/dnsmasq.d/vpn-domains-cloudflare.conf
#   config/domains/<X>.lst         -> /etc/dnsmasq.d/vpn-domains-<X>.conf
#
# Stale generated files are removed before regeneration, so deleting a list
# also deletes the corresponding dnsmasq config on the next run. The wipe
# also catches the legacy /etc/dnsmasq.d/vpn-domains.conf produced by the
# pre-v3.0.5 script.

set -euo pipefail

CONFIG_DIR="/opt/vpngateway/config"
DOMAINS_DIR="${CONFIG_DIR}/domains"
DNSMASQ_DIR="/etc/dnsmasq.d"
GEN_GLOB="${DNSMASQ_DIR}/vpn-domains*.conf"
IPSET_NAME="vpn_domains"

if [[ ! -d "$DOMAINS_DIR" ]]; then
    echo "ERROR: $DOMAINS_DIR not found" >&2
    exit 1
fi

# Wipe previous generation so removing a <category>.lst also drops its
# conf, and so the legacy `vpn-domains.conf` (no -<cat> suffix) from
# before v3.0.5 is cleaned up automatically.
shopt -s nullglob
for f in $GEN_GLOB; do
    rm -f "$f"
done
shopt -u nullglob

write_conf() {
    # write_conf <category> <domains_file>
    local category="$1" src="$2"
    local out="${DNSMASQ_DIR}/vpn-domains-${category}.conf"

    local domains=()
    # `|| [[ -n "$line" ]]` catches the last line if the file ends WITHOUT
    # a trailing newline. Plain `while read` returns false at EOF and
    # silently drops that line — historically that's how `medium.com`
    # disappeared between domains/main.lst and vpn-domains-main.conf
    # (CHANGELOG entry 59 / 66). Belt-and-suspenders even now that the
    # API normalises trailing newlines on write.
    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%%#*}"
        line="${line// /}"
        [[ -z "$line" ]] && continue
        domains+=("$line")
    done < "$src"

    if [[ ${#domains[@]} -eq 0 ]]; then
        cat > "$out" <<EOF
# Auto-generated from $(basename "$src") — no domains configured.
EOF
        echo "Generated $(basename "$out") (empty)"
        return
    fi

    cat > "$out" <<EOF
# Auto-generated by vpngw-update-domains.sh from domains/$(basename "$src")
# Resolved IPs are added to ipset ${IPSET_NAME}.
EOF

    # Build ipset directives: ipset=/dom1/dom2/.../<IPSET_NAME>
    # dnsmasq matches the listed domain AND all subdomains.
    #
    # Keep each directive short enough for older dnsmasq builds. OFFICE
    # deployments may have large local main.lst files (90+ domains), and
    # one huge ipset= line fails there with "bad option".
    local chunk_size=25
    local line="" n=0
    for d in "${domains[@]}"; do
        if [[ $n -eq 0 ]]; then
            line="ipset=/${d}/"
        else
            line+="${d}/"
        fi
        n=$((n + 1))
        if [[ $n -ge $chunk_size ]]; then
            echo "${line}${IPSET_NAME}" >> "$out"
            n=0
        fi
    done
    if [[ $n -gt 0 ]]; then
        echo "${line}${IPSET_NAME}" >> "$out"
    fi
    echo "Generated $(basename "$out") with ${#domains[@]} domains"
}

total=0
shopt -s nullglob
for src in "$DOMAINS_DIR"/*.lst; do
    category=$(basename "$src" .lst)
    write_conf "$category" "$src"
    total=$((total + 1))
done
shopt -u nullglob

if [[ $total -eq 0 ]]; then
    echo "WARNING: no *.lst files found in $DOMAINS_DIR"
fi

# Reload dnsmasq if running so the new directives take effect.
if systemctl is-active --quiet dnsmasq; then
    systemctl restart dnsmasq
    echo "dnsmasq restarted"
fi
